name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: save image
      run: docker save -o ./image foo:bar
    - name: Upload image
      uses: actions/upload-artifact@v1
      with:
      name: airflow-image
      path: image
