name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: define Docker tag
      run: echo "dockertag=my-image-name:$(git describe --always)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag git-$env:dockertag
    - name: save image
      run: docker save -o ./image ${dockertag}
    - name: Upload image
      uses: actions/upload-artifact@v1
      with:
        name: airflow-image
        path: image        
